"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')

# Gemini API Key
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY', 'your_gemini_api_key_here')
GROQ_API_KEY = os.environ.get('GROQ_API_KEY', '')
AI_PROVIDER = os.getenv('AI_PROVIDER', 'groq')
# Set true after enabling Zero Data Retention at https://console.groq.com/settings/data-controls
GROQ_ZDR_ENABLED = os.getenv('GROQ_ZDR_ENABLED', 'false').lower() == 'true'

# --- Archive / ZIP processing limits (tune via .env for large projects) ---
MAX_ZIP_UPLOAD_SIZE_MB = int(os.getenv('MAX_ZIP_UPLOAD_SIZE_MB', '200'))
DATA_UPLOAD_MAX_MEMORY_SIZE = MAX_ZIP_UPLOAD_SIZE_MB * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = MAX_ZIP_UPLOAD_SIZE_MB * 1024 * 1024

ZIP_MAX_FILES_TO_ANALYZE = int(os.getenv('ZIP_MAX_FILES_TO_ANALYZE', '150'))
ZIP_MAX_CHARS_PER_FILE = int(os.getenv('ZIP_MAX_CHARS_PER_FILE', '60000'))
ZIP_MAX_TOTAL_CHARS = int(os.getenv('ZIP_MAX_TOTAL_CHARS', '1200000'))
ZIP_BATCH_SIZE = int(os.getenv('ZIP_BATCH_SIZE', '10'))
ZIP_SINGLE_CALL_MAX_FILES = int(os.getenv('ZIP_SINGLE_CALL_MAX_FILES', '20'))
ZIP_SINGLE_CALL_MAX_CHARS = int(os.getenv('ZIP_SINGLE_CALL_MAX_CHARS', '200000'))
AI_BUNDLED_MAX_TOKENS = int(os.getenv('AI_BUNDLED_MAX_TOKENS', '16384'))
AI_SUMMARY_MAX_TOKENS = int(os.getenv('AI_SUMMARY_MAX_TOKENS', '8192'))
AI_REQUEST_TIMEOUT = float(os.getenv('AI_REQUEST_TIMEOUT', '300'))
ARCHIVE_PROCESS_ASYNC = os.getenv('ARCHIVE_PROCESS_ASYNC', 'true').lower() == 'true'

ZIP_ALLOWED_EXTENSIONS = {
    'html', 'css', 'js', 'jsx', 'ts', 'tsx', 'json', 'md', 'txt',
    'vue', 'svelte', 'scss', 'sass', 'less', 'xml', 'svg',
}
ZIP_IGNORED_DIRS = {
    'node_modules', 'build', 'dist', '.git', '.next', '.expo',
    'venv', 'env', '__pycache__', 'out', 'coverage', '.cache',
    'vendor', 'target', 'bin', 'obj', '.idea', '.vscode',
}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*hwl!q3p41tiqjur5f4+bti!gic0kv8khz9ks$zwd+13&@v%ca'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'feedback_app',
    'rest_framework_simplejwt',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'uiux_feedback',
        'USER': 'postgres',
        'PASSWORD': '8838', # REMINDER: Change this to your actual password
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Media files (uploaded designs)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS Settings (Allow React frontend to connect)
CORS_ALLOW_ALL_ORIGINS = True # For development only

# DRF Settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}
