# Generated by Django 6.0.2 on 2026-03-01 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='designs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_analysis', models.TextField()),
                ('ui_score', models.IntegerField(blank=True, null=True)),
                ('ux_score', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='feedback_app.design')),
            ],
        ),
        migrations.AddField(
            model_name='design',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='feedback_app.project'),
        ),
    ]
