# Generated by Django 6.0.1 on 2026-05-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0002_project_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aifeedback',
            name='ui_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='aifeedback',
            name='ux_score',
            field=models.IntegerField(default=0),
        ),
    ]
