# Generated by Django 6.0.2 on 2026-05-30 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0003_alter_aifeedback_ui_score_alter_aifeedback_ux_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='feedback_app.design')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to='archives/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archives', to='feedback_app.project')),
            ],
        ),
    ]
