# Generated by Django 6.0.1 on 2026-05-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectarchive',
            name='project_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
