# Generated by Django 6.0.1 on 2026-06-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0010_chatmessage_friendrequest_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectarchive',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
