# Generated by Django 5.2.17 on 2026-10-01 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback_app', '0012_alter_aifeedback_id_alter_chatmessage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hybridsubmission',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hybrid_submissions', to='feedback_app.project'),
        ),
    ]
